version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - APPLICATION_PORT=3000
      - "JWT_SECRET=CHANGE ME" #Change this to something long and unique
      - JWT_EXPIRATION=3d
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=sproot
      - STATE_UPDATE_INTERVAL=1000
      - DATABASE_UPDATE_INTERVAL=60000
    volumes:
      - ./docker_volumes/sproot/data:/home/sproot
    networks: 
      - sproot-network
    ports:
      - 3000:3000
    privileged: true
    command: ["sleep", "infinity"]

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./docker_volumes/mariadb/data:/var/lib/mysql
      - ./sproot-schema.sql:/docker-entrypoint-initdb.d/sproot-schema.sql
    networks:
      - sproot-network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - sproot-network
    ports:
      - 3001:8080

networks:
  sproot-network:
    driver: bridge

