version: "3"
services:
  server:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    environment:
      - NODE_ENV=production
      - DEFAULT_USER=dev-test #Change this to something unique
      - DEFAULT_USER_EMAIL=dev-test@example.com 
      - DEFAULT_USER_PASSWORD=password #Change this to something long and unique
      - APPLICATION_PORT=3000
      - AUTHENTICATION_ENABLED=true
      - JWT_SECRET="CHANGE ME" #Change this to something long and unique
      - JWT_EXPIRATION=3d
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root #**MATCH ME**
      - DATABASE_NAME=sproot
      - STATE_UPDATE_INTERVAL=1000
      - DATABASE_UPDATE_INTERVAL=60000
      - MAX_SENSOR_READING_CACHE_SIZE=10080 #7 days worth of minutes
      - INITIAL_CACHE_LOOKBACK=10080 #7 days in minutes
    volumes:
      - /sys:/sys
      - ./docker_volumes/sproot/server/logs:/sproot/server/logs
    networks:
      - sproot-network
    ports:
      - 3000:3000
    privileged: true
  
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_SPROOT_SERVER_URL=http://192.168.1.19:3000 #Match me to your api server
    volumes:
      - ./docker_volumes/sproot/client/logs:/sproot/logs
    networks:
      - sproot-network
    ports:
      - 3001:3000

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root #**MATCH ME**
    volumes:
      - ./docker_volumes/mariadb/data:/var/lib/mysql
      - ./sproot-schema.sql:/docker-entrypoint-initdb.d/sproot-schema.sql
    networks:
      - sproot-network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - sproot-network
    ports:
      - 3002:8080

networks:
  sproot-network:
    driver: bridge
