version: "3"
services:
  server:
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    environment:
      - NODE_ENV=production
      - DEFAULT_USER=dev-test #Change this to something unique
      - DEFAULT_USER_EMAIL=dev-test@example.com 
      - DEFAULT_USER_PASSWORD=password #Change this to something long and unique
      - APPLICATION_PORT=3000
      - AUTHENTICATION_ENABLED=false
      - JWT_SECRET="CHANGE ME" #Change this to something long and unique
      - JWT_EXPIRATION=3d
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root #**MATCH ME**
      - DATABASE_NAME=sproot
      - STATE_UPDATE_INTERVAL=1000
      - DATABASE_UPDATE_INTERVAL=60000
      - MAX_SENSOR_READING_CACHE_SIZE=10080 #7 days worth of minutes
      - INITIAL_CACHE_LOOKBACK=10080 #7 days in minutes
    volumes:
      - /sys:/sys
      - ./docker_volumes/sproot/server/logs:/sproot/server/logs
    networks:
      - sproot-network
    expose:
      - "3000"
    privileged: true
  
  client:
    restart: unless-stopped
    depends_on:
      - server
    build:
      context: ./
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_SERVER_URL: "" #SET THIS TO YOUR SERVER'S PUBLIC IP (ex. http://192.168.1.2)
    environment:
      NODE_ENV: production
    volumes:
      - ./docker_volumes/sproot/client/logs:/sproot/logs
    networks:
      - sproot-network
    ports:
      - 80:80

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root #**MATCH ME**
    volumes:
      - ./docker_volumes/mariadb/data:/var/lib/mysql
      - ./sproot-schema.sql:/docker-entrypoint-initdb.d/sproot-schema.sql
    networks:
      - sproot-network
    expose:
      - "3306"

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - sproot-network
    ports:
      - 3001:8080

networks:
  sproot-network:
    driver: bridge
