FROM --platform=$BUILDPLATFORM node:24.13.1-bookworm-slim AS build

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
  echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom; \
  echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom; \
  echo "Acquire::BrokenProxy true;" >> /etc/apt/apt.conf.d/99custom; \
  apt-get update; \
  apt-get install -y --no-install-recommends ca-certificates curl g++ git gnupg make nano python3; \
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg; \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list; \
  apt-get update; \
  apt-get install -y --no-install-recommends gh; \
  rm -rf /var/lib/apt/lists/*

# Copy project
COPY . /sproot
WORKDIR /sproot
ENV NODE_OPTIONS="--max-old-space-size=8192"
ARG VITE_VERSION
ARG VITE_API_SERVER_URL
RUN npm ci --workspace=common --workspace=client --workspace=docs \
  && npm run build:client \
  && npm run build:docs

FROM nginx:1.29.5-alpine-slim
RUN apk add --no-cache openssl iproute2
COPY --from=build ./sproot/client/dist /usr/share/nginx/html
COPY --from=build ./sproot/docs/build /usr/share/nginx/html/docs
COPY --from=build ./sproot/gateway/config/nginx.conf /etc/nginx/nginx.conf
COPY --from=build ./sproot/gateway/config/default.conf /etc/nginx/conf.d/default.conf
COPY --chmod=755 --from=build ./sproot/gateway/scripts/docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/docker-entrypoint.sh"]