SERVER_MODE = False
MASTER_PASSWORD_REQUIRED = False
ENHANCED_COOKIE_PROTECTION = False

DEFAULT_BINARY_PATHS = {
    "pg": "/usr/local/pgsql/bin"
}

MAX_SESSION_IDLE_TIME = 120
CONSOLE_LOG_LEVEL = 30

UPGRADE_CHECK_ENABLED = False
CHECK_SUPPORTED_BROWSER = False

ALLOW_SAVE_PASSWORD = True
SHOW_GRAVATAR_IMAGE = False

DATA_DIR = '/var/lib/pgadmin'
STORAGE_DIR = '/var/lib/pgadmin/storage'