export const Events = {
  AUTOMATIONS_TRIGGERED_EVENT: "automations.triggered",
  OUTPUT_ACTION_ADDED_EVENT: "output.action.added",
  OUTPUT_ACTION_DELETED_EVENT: "output.action.deleted",
  NOTIFICATION_ACTION_ADDED_EVENT: "notification.action.added",
  NOTIFICATION_ACTION_DELETED_EVENT: "notification.action.deleted",
  SENSOR_MODIFIED_EVENT: "sensor.modified",
  OUTPUT_MODIFIED_EVENT: "output.modified",
  CAMERA_SETTINGS_MODIFIED_EVENT: "camera.settings.modified",
  LOG_EVENT: "system.log.event",
  SENSOR_RETENTION_UPDATED: "sensor.retention.updated",
  OUTPUT_RETENTION_UPDATED: "output.retention.updated",
  BACKUP_RETENTION_UPDATED: "backup.retention.updated",
  SYSTEM_LOG_DEBUG_UPDATED: "system.log_debug.updated",
  SYSTEM_LATITUDE_UPDATED: "system.latitude.updated",
  SYSTEM_LONGITUDE_UPDATED: "system.longitude.updated",
} as const;
