FROM node:24.13.1-bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1

RUN set -eux; \
  echo "Acquire::http::Pipeline-Depth 0;" > /etc/apt/apt.conf.d/99custom; \
  echo "Acquire::http::No-Cache true;" >> /etc/apt/apt.conf.d/99custom; \
  echo "Acquire::BrokenProxy true;" >> /etc/apt/apt.conf.d/99custom; \
  apt-get update; \
  apt-get install -y --no-install-recommends ca-certificates curl g++ git gnupg make nano python3 python3-pip udev wget; \
  curl -fsSL https://archive.raspberrypi.org/debian/raspberrypi.gpg.key \
    | gpg --dearmor -o /usr/share/keyrings/raspberrypi-archive-keyring.gpg; \
  echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] https://archive.raspberrypi.org/debian/ bookworm main" > /etc/apt/sources.list.d/raspi.list; \
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg; \
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list; \
  install -d /usr/share/postgresql-common/pgdg; \
  wget --quiet -O /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc; \
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list; \
  apt-get update; \
  apt-get install -y --no-install-recommends gh postgresql-client-18 python3-picamera2; \
  pip3 install --no-cache-dir fastapi uvicorn --break-system-packages; \
  rm -rf /var/lib/apt/lists/*

# Copy project
COPY . /sproot
WORKDIR /sproot
RUN set -eux; \
  install -d /var/lib/sproot/server/logs /var/lib/sproot/server/images /var/lib/sproot/server/certs /var/lib/sproot/server/backups; \
  rm -rf /sproot/server/logs /sproot/server/images /sproot/server/certs /sproot/server/backups; \
  ln -s /var/lib/sproot/server/logs /sproot/server/logs; \
  ln -s /var/lib/sproot/server/images /sproot/server/images; \
  ln -s /var/lib/sproot/server/certs /sproot/server/certs; \
  ln -s /var/lib/sproot/server/backups /sproot/server/backups
RUN npm ci --workspace=common --workspace=server \
  && npm run build:server

# Expose app ports
EXPOSE 3000
