import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStarted: [
    { type: 'autogenerated', dirName: 'getting-started' }],
  howTo: [
    { type: 'autogenerated', dirName: 'how-to' }],

};

export default sidebars;
