name: "Workflow"

on:
  push:
    branches: ["**"]

jobs:
  prettier:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Check code style
        run: npm run prettier:check

  test:
    needs: prettier
    name: Run Tests (Node ${{ matrix.node-version }}) ${{ matrix.experimental && '(experimental)' || '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 22.5.1
            experimental: false
          - node-version: 22.x
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  docker-test:
    needs: [prettier, test]
    name: Test Docker Compose Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Build docker images
        run: docker compose --env-file .env.production build